/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness and database check */
        get: operations["AppController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a base64 image and get a media id back */
        post: operations["MediaController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Media metadata */
        get: operations["MediaController_metadata"];
        put?: never;
        post?: never;
        /** Soft-delete your own media */
        delete: operations["MediaController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{id}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Original image bytes */
        get: operations["MediaController_raw"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/{id}/thumbnail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Thumbnail bytes — use this in lists */
        get: operations["MediaController_thumbnail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account. Terms must be accepted here. */
        post: operations["AuthController_signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in and receive an access + refresh token pair */
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange a refresh token for a new pair (rotating) */
        post: operations["AuthController_refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a single refresh token */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke every session for the current user */
        post: operations["AuthController_logoutAll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user, including whether new terms need accepting */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/accept-terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept the current terms version */
        post: operations["AuthController_acceptTerms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change password and sign out every session */
        post: operations["AuthController_changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Deactivate your account */
        delete: operations["UsersController_deactivate"];
        options?: never;
        head?: never;
        /** Update your profile */
        patch: operations["UsersController_updateProfile"];
        trace?: never;
    };
    "/api/users/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Find someone by their exact email, to send a friend request */
        get: operations["UsersController_lookup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** People you are connected to */
        get: operations["FriendshipsController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a friend request by email or user id */
        post: operations["FriendshipsController_send"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/requests/incoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requests waiting for your answer */
        get: operations["FriendshipsController_incoming"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/requests/outgoing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Requests you have sent */
        get: operations["FriendshipsController_outgoing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/requests/{id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept a friend request */
        post: operations["FriendshipsController_accept"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/requests/{id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject a friend request */
        post: operations["FriendshipsController_reject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Disconnect from someone (place access is unaffected) */
        delete: operations["FriendshipsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/friends/{userId}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Block someone from contacting you */
        post: operations["FriendshipsController_block"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Places you own or that are shared with you */
        get: operations["PlacesController_findAll"];
        put?: never;
        /** Create a house / office / locker */
        post: operations["PlacesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One place with its members and counts */
        get: operations["PlacesController_findOne"];
        put?: never;
        post?: never;
        /** Soft-delete a place and everything inside it */
        delete: operations["PlacesController_remove"];
        options?: never;
        head?: never;
        /** Update place details */
        patch: operations["PlacesController_update"];
        trace?: never;
    };
    "/api/places/{placeId}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Who did what in this place */
        get: operations["PlacesController_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem an invite code and join that place */
        post: operations["MembersController_acceptInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everyone with access to this place */
        get: operations["MembersController_list"];
        put?: never;
        /** Add an accepted friend to this place */
        post: operations["MembersController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/members/{memberId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove someone from this place */
        delete: operations["MembersController_remove"];
        options?: never;
        head?: never;
        /** Change what someone can do in this place */
        patch: operations["MembersController_updateRole"];
        trace?: never;
    };
    "/api/places/{placeId}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Leave a place you were added to */
        post: operations["MembersController_leave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invite codes that are still open */
        get: operations["MembersController_listInvites"];
        put?: never;
        /** Create an invite code for someone not on the app yet */
        post: operations["MembersController_createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/invites/{inviteId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an unused invite code */
        delete: operations["MembersController_revokeInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/storages/by-label/{labelCode}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Look up a storage by its QR sticker code, across all your places */
        get: operations["StoragesController_findByLabel"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/storages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Flat list of storages — this feeds the dropdown when adding a thing */
        get: operations["StoragesController_findAll"];
        put?: never;
        /** Add a storage. Pass parentId to nest it inside another one. */
        post: operations["StoragesController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/storages/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Nested tree of every storage in the place */
        get: operations["StoragesController_tree"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/storages/{storageId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One storage with its children and the items inside it */
        get: operations["StoragesController_findOne"];
        put?: never;
        post?: never;
        /** Delete a storage and its subtree; items inside become unassigned */
        delete: operations["StoragesController_remove"];
        options?: never;
        head?: never;
        /** Rename, edit, or move a storage (with its whole subtree) */
        patch: operations["StoragesController_update"];
        trace?: never;
    };
    "/api/items/attention": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Expiring, out-of-warranty, overdue-to-return and low-stock items everywhere */
        get: operations["ItemsController_attention"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and filter the things in a place */
        get: operations["ItemsController_findAll"];
        put?: never;
        /** Add a thing and say which storage it went into */
        post: operations["ItemsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One thing, with its photos and recent movements */
        get: operations["ItemsController_findOne"];
        put?: never;
        post?: never;
        /** Soft-delete a thing */
        delete: operations["ItemsController_remove"];
        options?: never;
        head?: never;
        /** Edit a thing */
        patch: operations["ItemsController_update"];
        trace?: never;
    };
    "/api/places/{placeId}/items/{itemId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Everywhere this thing has been kept */
        get: operations["ItemsController_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/items/{itemId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move a thing to another storage */
        post: operations["ItemsController_move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/items/{itemId}/lend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a thing as lent out */
        post: operations["ItemsController_lend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/places/{placeId}/items/{itemId}/return": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a lent thing as returned */
        post: operations["ItemsController_returnItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find a thing across every place you can see
         * @description Typo-tolerant: "almira" finds "Almirah". Alias-aware: "charger" finds "Type-C cable". Each result comes back with the full breadcrumb of where it is kept.
         */
        get: operations["SearchController_search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * @example up
             * @enum {string}
             */
            database: "up" | "down";
            /** Format: date-time */
            timestamp: string;
        };
        CreateMediaDto: {
            /** @description Image as base64. A data URI ("data:image/jpeg;base64,...") or raw base64 both work. */
            base64: string;
            /** @description Optional caption/filename, stored for reference only */
            label?: string;
        };
        MediaResponse: {
            /**
             * Format: uuid
             * @description Use this id when creating an item or storage
             */
            id: string;
            /** Format: uuid */
            ownerId: string;
            /** @example image/jpeg */
            mimeType: string;
            /** @example 284913 */
            sizeBytes: number;
            /** @example 1600 */
            width: Record<string, never> | null;
            /** @example 1200 */
            height: Record<string, never> | null;
            /** @description SHA-256 — re-uploading the same photo reuses the stored file */
            checksum: string;
            /** Format: date-time */
            createdAt: string;
        };
        SuccessResponse: {
            /** @example true */
            success: boolean;
            /** @example Home — Demo deleted */
            message?: string;
        };
        SignupDto: {
            /** @example shristi@example.com */
            email: string;
            /** @example Shristi Gupta */
            name: string;
            /** @example Str0ng#Pass */
            password: string;
            /** @example +919876543210 */
            phone?: string;
            /**
             * @description Must be true. The accepted version is recorded server-side.
             * @example true
             */
            acceptTerms: boolean;
        };
        UserProfileResponse: {
            /** Format: uuid */
            id: string;
            /** @example shristi@example.com */
            email: string;
            /** @example Shristi Gupta */
            name: string;
            /** @example +919876543210 */
            phone: Record<string, never> | null;
            /** Format: uuid */
            avatarMediaId: Record<string, never> | null;
            /** @example 2026-09-01 */
            termsVersion: Record<string, never> | null;
            /** Format: date-time */
            termsAcceptedAt: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        SignupResponse: {
            /** @description Send as: Authorization: Bearer <accessToken> */
            accessToken: string;
            /** @description Single use — every refresh returns a new one */
            refreshToken: string;
            /**
             * @description Lifetime of the access token
             * @example 15m
             */
            expiresIn: string;
            user: components["schemas"]["UserProfileResponse"];
        };
        LoginDto: {
            /** @example shristi@example.com */
            email: string;
            /** @example Str0ng#Pass */
            password: string;
        };
        LoginResponse: {
            /** @description Send as: Authorization: Bearer <accessToken> */
            accessToken: string;
            /** @description Single use — every refresh returns a new one */
            refreshToken: string;
            /**
             * @description Lifetime of the access token
             * @example 15m
             */
            expiresIn: string;
            user: components["schemas"]["UserProfileResponse"];
            /** @example false */
            termsAcceptanceRequired: boolean;
            /** @example 2026-09-01 */
            currentTermsVersion: string;
        };
        RefreshDto: {
            /** @description The refresh token issued at login or last refresh */
            refreshToken: string;
        };
        TokenPairResponse: {
            /** @description Send as: Authorization: Bearer <accessToken> */
            accessToken: string;
            /** @description Single use — every refresh returns a new one */
            refreshToken: string;
            /**
             * @description Lifetime of the access token
             * @example 15m
             */
            expiresIn: string;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            /** @example shristi@example.com */
            email: string;
            /** @example Shristi Gupta */
            name: string;
            /** @example +919876543210 */
            phone: Record<string, never> | null;
            /** Format: uuid */
            avatarMediaId: Record<string, never> | null;
            /** @example 2026-09-01 */
            termsVersion: Record<string, never> | null;
            /** Format: date-time */
            termsAcceptedAt: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * @description When true, show the terms dialog — other routes will return 403 until accepted
             * @example false
             */
            termsAcceptanceRequired: boolean;
            /** @example 2026-09-01 */
            currentTermsVersion: string;
        };
        AcceptTermsDto: {
            /** @example true */
            accept: boolean;
            /** @description Version being accepted. Must match the current server version when provided. */
            version?: string;
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        ChangePasswordResponse: {
            /** @example true */
            success: boolean;
            /** @example Password changed. Please sign in again. */
            message?: string;
        };
        UpdateProfileDto: {
            name?: string;
            phone?: string;
            /** @description Base64 avatar image */
            avatarBase64?: string;
        };
        UserCard: {
            /** Format: uuid */
            id: string;
            /** @example Shristi */
            name: string;
            /** @example shristi@example.com */
            email?: string;
            /** Format: uuid */
            avatarMediaId?: Record<string, never> | null;
        };
        FriendResponse: {
            /** Format: uuid */
            friendshipId: string;
            /** Format: date-time */
            since: Record<string, never> | null;
            /** @description The other person, whoever sent the request */
            user: components["schemas"]["UserCard"];
        };
        CreateFriendRequestDto: {
            /** @description Either email or userId is required */
            email?: string;
            userId?: string;
            /** @example Hi Mummy, adding you so you can see the almirah */
            message?: string;
        };
        FriendshipResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "REJECTED" | "BLOCKED";
            /** @example Hi Mummy, adding you */
            message: Record<string, never> | null;
            requester: components["schemas"]["UserCard"];
            addressee: components["schemas"]["UserCard"];
            /** Format: date-time */
            respondedAt: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        CreatePlaceDto: {
            /** @example Home — Sector 62 */
            name: string;
            /**
             * @default HOME
             * @enum {string}
             */
            type: "HOME" | "OFFICE" | "LOCKER" | "VEHICLE" | "STORAGE_UNIT" | "OTHER";
            description?: string;
            /** @description Optional — most people never measure their rooms */
            widthValue?: number;
            lengthValue?: number;
            heightValue?: number;
            /** @enum {string} */
            lengthUnit?: "CM" | "INCH";
            addressLine?: string;
            city?: string;
            country?: string;
            /** @example 28.6139 */
            latitude?: number;
            /** @example 77.209 */
            longitude?: number;
            /** @description Base64 cover photo of the place */
            coverImageBase64?: string;
        };
        PlaceResponse: {
            /** Format: uuid */
            id: string;
            /** @example Home — Sector 62 */
            name: string;
            /** @enum {string} */
            type: "HOME" | "OFFICE" | "LOCKER" | "VEHICLE" | "STORAGE_UNIT" | "OTHER";
            description: Record<string, never> | null;
            /** Format: uuid */
            ownerId: string;
            /** @example Noida */
            city: Record<string, never> | null;
            /** @example India */
            country: Record<string, never> | null;
            /** @example 28.6139 */
            latitude: Record<string, never> | null;
            /** @example 77.209 */
            longitude: Record<string, never> | null;
            /** Format: uuid */
            coverMediaId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        PlaceListItemResponse: {
            /** Format: uuid */
            id: string;
            /** @example Home — Sector 62 */
            name: string;
            /** @enum {string} */
            type: "HOME" | "OFFICE" | "LOCKER" | "VEHICLE" | "STORAGE_UNIT" | "OTHER";
            description: Record<string, never> | null;
            /** Format: uuid */
            ownerId: string;
            /** @example Noida */
            city: Record<string, never> | null;
            /** @example India */
            country: Record<string, never> | null;
            /** @example 28.6139 */
            latitude: Record<string, never> | null;
            /** @example 77.209 */
            longitude: Record<string, never> | null;
            /** Format: uuid */
            coverMediaId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * @description Your role in this place
             * @enum {string}
             */
            myRole: "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";
            /** @example 2 */
            memberCount: number;
            members: components["schemas"]["UserCard"][];
            /** @example 5 */
            storageCount: number;
            /**
             * @description Excludes other people's private items
             * @example 12
             */
            itemCount: number;
        };
        PlaceMemberResponse: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";
            /** @enum {string} */
            status: "INVITED" | "ACTIVE" | "REMOVED";
            /** Format: date-time */
            joinedAt: Record<string, never> | null;
            user: components["schemas"]["UserCard"];
            invitedBy?: components["schemas"]["UserCard"] | null;
        };
        PlaceDetailResponse: {
            /** Format: uuid */
            id: string;
            /** @example Home — Sector 62 */
            name: string;
            /** @enum {string} */
            type: "HOME" | "OFFICE" | "LOCKER" | "VEHICLE" | "STORAGE_UNIT" | "OTHER";
            description: Record<string, never> | null;
            /** Format: uuid */
            ownerId: string;
            /** @example Noida */
            city: Record<string, never> | null;
            /** @example India */
            country: Record<string, never> | null;
            /** @example 28.6139 */
            latitude: Record<string, never> | null;
            /** @example 77.209 */
            longitude: Record<string, never> | null;
            /** Format: uuid */
            coverMediaId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            owner: components["schemas"]["UserCard"];
            members: components["schemas"]["PlaceMemberResponse"][];
            /** @enum {string} */
            myRole: "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";
            /** @example 5 */
            storageCount: number;
            /** @example 12 */
            itemCount: number;
        };
        UpdatePlaceDto: {
            /** @example Home — Sector 62 */
            name?: string;
            /**
             * @default HOME
             * @enum {string}
             */
            type: "HOME" | "OFFICE" | "LOCKER" | "VEHICLE" | "STORAGE_UNIT" | "OTHER";
            description?: string;
            /** @description Optional — most people never measure their rooms */
            widthValue?: number;
            lengthValue?: number;
            heightValue?: number;
            /** @enum {string} */
            lengthUnit?: "CM" | "INCH";
            addressLine?: string;
            city?: string;
            country?: string;
            /** @example 28.6139 */
            latitude?: number;
            /** @example 77.209 */
            longitude?: number;
            /** @description Base64 cover photo of the place */
            coverImageBase64?: string;
        };
        ActivityLogResponse: {
            /** Format: uuid */
            id: string;
            /** @example ITEM_MOVED */
            action: string;
            /** @example Item */
            entityType: string;
            /** Format: uuid */
            entityId: Record<string, never> | null;
            /** @example Moved "Passport" to Bedroom › Almirah › Top shelf */
            summary: string;
            actor: components["schemas"]["UserCard"];
            /** Format: date-time */
            createdAt: string;
        };
        AcceptInviteDto: {
            /** @example FMS-INV-7K3QX2 */
            code: string;
        };
        AddMemberDto: {
            /** @description Must already be an accepted friend */
            userId: string;
            /**
             * @default MEMBER
             * @enum {string}
             */
            role: "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";
        };
        UpdateMemberDto: {
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";
        };
        CreateInviteDto: {
            /** @description Who the invite is for — used to prefill and to notify */
            email?: string;
            phone?: string;
            /**
             * @default MEMBER
             * @enum {string}
             */
            role: "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";
            /** @default 7 */
            expiresInDays: number;
        };
        PlaceInviteResponse: {
            /** Format: uuid */
            id: string;
            /**
             * @description Share this code with the person
             * @example INV-ZJ5Y0YAP
             */
            code: string;
            /** @example mum@example.com */
            email: Record<string, never> | null;
            phone: Record<string, never> | null;
            /** @enum {string} */
            role: "OWNER" | "ADMIN" | "MEMBER" | "VIEWER";
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            acceptedAt: Record<string, never> | null;
        };
        StorageResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            placeId: string;
            /**
             * Format: uuid
             * @description Null for a top-level storage
             */
            parentId: Record<string, never> | null;
            /** @example Almirah */
            name: string;
            /** @enum {string} */
            type: "ROOM" | "ALMIRAH" | "WARDROBE" | "CABINET" | "SHELF" | "DRAWER" | "BED" | "BOX" | "SUITCASE" | "BAG" | "FRIDGE" | "LOFT" | "RACK" | "DESK" | "SAFE" | "OTHER";
            description: Record<string, never> | null;
            /**
             * @description Ancestor ids, root first, slash separated. Empty for a root storage.
             * @example 3f2a…/9b1c…
             */
            path: string;
            /**
             * @description Depth in the tree; 0 is top level
             * @example 2
             */
            level: number;
            /**
             * @description Print this as a QR sticker on the box
             * @example FMS-7K3QX2
             */
            labelCode: string;
            /** Format: uuid */
            coverMediaId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
        };
        StorageDetailResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            placeId: string;
            /**
             * Format: uuid
             * @description Null for a top-level storage
             */
            parentId: Record<string, never> | null;
            /** @example Almirah */
            name: string;
            /** @enum {string} */
            type: "ROOM" | "ALMIRAH" | "WARDROBE" | "CABINET" | "SHELF" | "DRAWER" | "BED" | "BOX" | "SUITCASE" | "BAG" | "FRIDGE" | "LOFT" | "RACK" | "DESK" | "SAFE" | "OTHER";
            description: Record<string, never> | null;
            /**
             * @description Ancestor ids, root first, slash separated. Empty for a root storage.
             * @example 3f2a…/9b1c…
             */
            path: string;
            /**
             * @description Depth in the tree; 0 is top level
             * @example 2
             */
            level: number;
            /**
             * @description Print this as a QR sticker on the box
             * @example FMS-7K3QX2
             */
            labelCode: string;
            /** Format: uuid */
            coverMediaId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** @example Bedroom › Almirah › Top shelf */
            breadcrumb: string;
            /** @description Direct children only */
            children: components["schemas"]["StorageResponse"][];
            /** @description Items directly inside this storage */
            items?: Record<string, never>[];
        };
        CreateStorageDto: {
            /** @example Almirah */
            name: string;
            /**
             * @default OTHER
             * @enum {string}
             */
            type: "ROOM" | "ALMIRAH" | "WARDROBE" | "CABINET" | "SHELF" | "DRAWER" | "BED" | "BOX" | "SUITCASE" | "BAG" | "FRIDGE" | "LOFT" | "RACK" | "DESK" | "SAFE" | "OTHER";
            /** @description Parent storage id. Omit for a top-level storage such as a room. */
            parentId?: string;
            description?: string;
            widthValue?: number;
            lengthValue?: number;
            heightValue?: number;
            /** @enum {string} */
            lengthUnit?: "CM" | "INCH";
            /** @description Useful for a bank locker or a box kept elsewhere */
            latitude?: number;
            longitude?: number;
            /** @description Base64 photo of the storage, e.g. the open almirah */
            coverImageBase64?: string;
        };
        StorageListItemResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            placeId: string;
            /**
             * Format: uuid
             * @description Null for a top-level storage
             */
            parentId: Record<string, never> | null;
            /** @example Almirah */
            name: string;
            /** @enum {string} */
            type: "ROOM" | "ALMIRAH" | "WARDROBE" | "CABINET" | "SHELF" | "DRAWER" | "BED" | "BOX" | "SUITCASE" | "BAG" | "FRIDGE" | "LOFT" | "RACK" | "DESK" | "SAFE" | "OTHER";
            description: Record<string, never> | null;
            /**
             * @description Ancestor ids, root first, slash separated. Empty for a root storage.
             * @example 3f2a…/9b1c…
             */
            path: string;
            /**
             * @description Depth in the tree; 0 is top level
             * @example 2
             */
            level: number;
            /**
             * @description Print this as a QR sticker on the box
             * @example FMS-7K3QX2
             */
            labelCode: string;
            /** Format: uuid */
            coverMediaId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /**
             * @description Ready to render — ancestor names resolved at read time
             * @example Bedroom › Almirah › Top shelf
             */
            breadcrumb: string;
            /** @example 4 */
            itemCount: number;
        };
        StorageNodeResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            placeId: string;
            /**
             * Format: uuid
             * @description Null for a top-level storage
             */
            parentId: Record<string, never> | null;
            /** @example Almirah */
            name: string;
            /** @enum {string} */
            type: "ROOM" | "ALMIRAH" | "WARDROBE" | "CABINET" | "SHELF" | "DRAWER" | "BED" | "BOX" | "SUITCASE" | "BAG" | "FRIDGE" | "LOFT" | "RACK" | "DESK" | "SAFE" | "OTHER";
            description: Record<string, never> | null;
            /**
             * @description Ancestor ids, root first, slash separated. Empty for a root storage.
             * @example 3f2a…/9b1c…
             */
            path: string;
            /**
             * @description Depth in the tree; 0 is top level
             * @example 2
             */
            level: number;
            /**
             * @description Print this as a QR sticker on the box
             * @example FMS-7K3QX2
             */
            labelCode: string;
            /** Format: uuid */
            coverMediaId: Record<string, never> | null;
            /** Format: date-time */
            createdAt: string;
            /** @description Nested child storages */
            children: components["schemas"]["StorageNodeResponse"][];
            /** @example 4 */
            itemCount: number;
        };
        UpdateStorageDto: {
            /** @example Almirah */
            name?: string;
            /**
             * @default OTHER
             * @enum {string}
             */
            type: "ROOM" | "ALMIRAH" | "WARDROBE" | "CABINET" | "SHELF" | "DRAWER" | "BED" | "BOX" | "SUITCASE" | "BAG" | "FRIDGE" | "LOFT" | "RACK" | "DESK" | "SAFE" | "OTHER";
            description?: string;
            widthValue?: number;
            lengthValue?: number;
            heightValue?: number;
            /** @enum {string} */
            lengthUnit?: "CM" | "INCH";
            /** @description Useful for a bank locker or a box kept elsewhere */
            latitude?: number;
            longitude?: number;
            /** @description Base64 photo of the storage, e.g. the open almirah */
            coverImageBase64?: string;
            /** @description Move this storage (and everything inside it) under another storage. Pass null to move it to the top level. */
            parentId?: Record<string, never> | null;
        };
        StorageDeletedResponse: {
            /** @example true */
            success: boolean;
            /** @example Deleted 3 storage(s). 7 item(s) are now unassigned. */
            message: string;
            /**
             * @description Storages soft-deleted, including the subtree
             * @example 3
             */
            storages: number;
            /**
             * @description Items that became unassigned rather than deleted
             * @example 7
             */
            items: number;
        };
        AttentionItemResponse: {
            /** Format: uuid */
            id: string;
            /** @example Paracetamol strip */
            name: string;
            /** @example 2 */
            quantity: number;
            /** Format: date-time */
            expiresAt: Record<string, never> | null;
            storage?: Record<string, never> | null;
            place?: Record<string, never>;
        };
        AttentionResponse: {
            /** @description Expiring soon or already expired */
            expiring: components["schemas"]["AttentionItemResponse"][];
            /** @description Warranty running out */
            warranty: components["schemas"]["AttentionItemResponse"][];
            /** @description Lent out and past the due date */
            overdue: components["schemas"]["AttentionItemResponse"][];
            /** @description At or below the low-stock threshold */
            lowStock: components["schemas"]["AttentionItemResponse"][];
        };
        CreateItemDto: {
            /** @example Passport */
            name: string;
            /** @description Where it is kept. Omit if not put away yet. */
            storageId?: string;
            description?: string;
            /**
             * @description Other names you might search by, e.g. ["charger"] for a Type-C cable
             * @example [
             *       "charger",
             *       "cable"
             *     ]
             */
            aliases?: string[];
            /**
             * @example [
             *       "documents",
             *       "important"
             *     ]
             */
            tags?: string[];
            /** @example Documents */
            category?: string;
            /** @default 1 */
            quantity: number;
            /** @description Warn when quantity drops to this number */
            lowStockAt?: number;
            serialNumber?: string;
            /**
             * @description PRIVATE hides this item from every other member of the place
             * @default SHARED
             * @enum {string}
             */
            visibility: "SHARED" | "PRIVATE";
            latitude?: number;
            longitude?: number;
            /** @example 2026-01-15T00:00:00.000Z */
            purchasedAt?: string;
            /** @description Medicines, food, documents */
            expiresAt?: string;
            warrantyUntil?: string;
            /** @description Remind me about this item at this time */
            remindAt?: string;
            /** @description Base64 photos of where it is kept. First one becomes the cover. */
            imagesBase64?: string[];
        };
        ItemStorageRef: {
            /** Format: uuid */
            id: string;
            /** @example Top shelf */
            name: string;
            /**
             * @description Where the thing is — render this directly
             * @example Bedroom › Almirah › Top shelf
             */
            breadcrumb: string;
        };
        ItemMovementResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            fromStorageId: Record<string, never> | null;
            /** Format: uuid */
            toStorageId: Record<string, never> | null;
            /** @example Bedroom › Almirah › Top shelf */
            fromLabel: Record<string, never> | null;
            /** @example Bedroom › Under the bed › Blue box */
            toLabel: Record<string, never> | null;
            /** @example Shifted while cleaning */
            note: Record<string, never> | null;
            movedBy: components["schemas"]["UserCard"];
            /** Format: date-time */
            createdAt: string;
        };
        ItemDetailResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            placeId: string;
            /** @example Passport */
            name: string;
            /** @example Inside the brown document folder */
            description: Record<string, never> | null;
            /**
             * @example [
             *       "charger",
             *       "cable"
             *     ]
             */
            aliases: string[];
            /**
             * @example [
             *       "documents",
             *       "important"
             *     ]
             */
            tags: string[];
            /** @example Documents */
            category: Record<string, never> | null;
            /** @example 1 */
            quantity: number;
            /** @example 1 */
            lowStockAt: Record<string, never> | null;
            /** @enum {string} */
            status: "AVAILABLE" | "LENT_OUT" | "CONSUMED" | "LOST" | "DISCARDED";
            /**
             * @description PRIVATE is visible only to ownerId
             * @enum {string}
             */
            visibility: "SHARED" | "PRIVATE";
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            expiresAt: Record<string, never> | null;
            /** Format: date-time */
            warrantyUntil: Record<string, never> | null;
            /** @example Rahul (neighbour) */
            lentToName: Record<string, never> | null;
            /** Format: date-time */
            dueAt: Record<string, never> | null;
            storage: components["schemas"]["ItemStorageRef"] | null;
            /** @description Fetch each at /media/{id}/thumbnail or /media/{id}/raw */
            mediaIds: string[];
            /** Format: date-time */
            updatedAt: string;
            owner: components["schemas"]["UserCard"];
            createdBy: components["schemas"]["UserCard"];
            /** @description 20 most recent moves */
            movements: components["schemas"]["ItemMovementResponse"][];
        };
        ItemResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            placeId: string;
            /** @example Passport */
            name: string;
            /** @example Inside the brown document folder */
            description: Record<string, never> | null;
            /**
             * @example [
             *       "charger",
             *       "cable"
             *     ]
             */
            aliases: string[];
            /**
             * @example [
             *       "documents",
             *       "important"
             *     ]
             */
            tags: string[];
            /** @example Documents */
            category: Record<string, never> | null;
            /** @example 1 */
            quantity: number;
            /** @example 1 */
            lowStockAt: Record<string, never> | null;
            /** @enum {string} */
            status: "AVAILABLE" | "LENT_OUT" | "CONSUMED" | "LOST" | "DISCARDED";
            /**
             * @description PRIVATE is visible only to ownerId
             * @enum {string}
             */
            visibility: "SHARED" | "PRIVATE";
            /** Format: uuid */
            ownerId: string;
            /** Format: date-time */
            expiresAt: Record<string, never> | null;
            /** Format: date-time */
            warrantyUntil: Record<string, never> | null;
            /** @example Rahul (neighbour) */
            lentToName: Record<string, never> | null;
            /** Format: date-time */
            dueAt: Record<string, never> | null;
            storage: components["schemas"]["ItemStorageRef"] | null;
            /** @description Fetch each at /media/{id}/thumbnail or /media/{id}/raw */
            mediaIds: string[];
            /** Format: date-time */
            updatedAt: string;
        };
        PaginationMeta: {
            /** @example 1 */
            page: number;
            /** @example 20 */
            limit: number;
            /** @example 37 */
            total: number;
            /** @example 2 */
            totalPages: number;
            /** @example true */
            hasNext: boolean;
        };
        PaginatedItemsResponse: {
            data: components["schemas"]["ItemResponse"][];
            meta: components["schemas"]["PaginationMeta"];
        };
        UpdateItemDto: {
            /** @example Passport */
            name?: string;
            description?: string;
            /**
             * @description Other names you might search by, e.g. ["charger"] for a Type-C cable
             * @example [
             *       "charger",
             *       "cable"
             *     ]
             */
            aliases?: string[];
            /**
             * @example [
             *       "documents",
             *       "important"
             *     ]
             */
            tags?: string[];
            /** @example Documents */
            category?: string;
            /** @default 1 */
            quantity: number;
            /** @description Warn when quantity drops to this number */
            lowStockAt?: number;
            serialNumber?: string;
            /**
             * @description PRIVATE hides this item from every other member of the place
             * @default SHARED
             * @enum {string}
             */
            visibility: "SHARED" | "PRIVATE";
            latitude?: number;
            longitude?: number;
            /** @example 2026-01-15T00:00:00.000Z */
            purchasedAt?: string;
            /** @description Medicines, food, documents */
            expiresAt?: string;
            warrantyUntil?: string;
            /** @description Remind me about this item at this time */
            remindAt?: string;
            /** @description Base64 photos of where it is kept. First one becomes the cover. */
            imagesBase64?: string[];
            /** @description Move the item. Pass null to mark it as not put away anywhere. */
            storageId?: Record<string, never> | null;
        };
        MoveItemDto: {
            /** @description Destination storage, or null to unassign */
            toStorageId: Record<string, never> | null;
            /** @example Shifted while cleaning */
            note?: string;
        };
        LendItemDto: {
            /** @example Rahul (neighbour) */
            lentToName: string;
            /** @description App user id, when you lent it to someone on FindMyStuff */
            lentToId?: string;
            /** @description When you expect it back */
            dueAt?: string;
        };
        PlaceCard: {
            /** Format: uuid */
            id: string;
            /** @example Home — Sector 62 */
            name: string;
        };
        SearchItemStorage: {
            /** Format: uuid */
            id: string;
            /** @example Top shelf */
            name: string;
            /**
             * @description Includes the place name — this is the answer to "where did I keep it"
             * @example Home › Bedroom › Almirah › Top shelf
             */
            breadcrumb: string;
        };
        SearchItemResult: {
            /** Format: uuid */
            id: string;
            /** @example Passport */
            name: string;
            description: Record<string, never> | null;
            tags: string[];
            aliases: string[];
            /** @example 1 */
            quantity: number;
            /** @enum {string} */
            status: "AVAILABLE" | "LENT_OUT" | "CONSUMED" | "LOST" | "DISCARDED";
            /** Format: date-time */
            expiresAt: Record<string, never> | null;
            /**
             * Format: uuid
             * @description Cover photo, if any
             */
            mediaId: Record<string, never> | null;
            place: components["schemas"]["PlaceCard"];
            storage: components["schemas"]["SearchItemStorage"] | null;
            /**
             * @description Relevance; results are already sorted by it
             * @example 2.43
             */
            score: number;
            /** Format: date-time */
            updatedAt: string;
        };
        SearchStorageResult: {
            /** Format: uuid */
            id: string;
            /** @example Almirah */
            name: string;
            /** @example ALMIRAH */
            type: string;
            /** @example FMS-0QN5EP */
            labelCode: string;
            /** @example 4 */
            itemCount: number;
            place: components["schemas"]["PlaceCard"];
            /** @example Home › Bedroom › Almirah */
            breadcrumb: string;
        };
        SearchResponse: {
            /**
             * @description Echo of what was searched
             * @example charger
             */
            query: string;
            items: components["schemas"]["SearchItemResult"][];
            /** @description Pagination for items only */
            meta: components["schemas"]["PaginationMeta"];
            /** @description Storages whose own name matched, capped at 10 */
            storages: components["schemas"]["SearchStorageResult"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    MediaController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMediaDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponse"];
                };
            };
        };
    };
    MediaController_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MediaResponse"];
                };
            };
        };
    };
    MediaController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    MediaController_raw: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "image/webp": string;
                };
            };
        };
    };
    MediaController_thumbnail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/webp": string;
                };
            };
        };
    };
    AuthController_signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignupResponse"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
        };
    };
    AuthController_refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    AuthController_logoutAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    AuthController_acceptTerms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptTermsDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    AuthController_changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePasswordResponse"];
                };
            };
        };
    };
    UsersController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    UsersController_updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfileResponse"];
                };
            };
        };
    };
    UsersController_lookup: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCard"];
                };
            };
        };
    };
    FriendshipsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendResponse"][];
                };
            };
        };
    };
    FriendshipsController_send: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFriendRequestDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"];
                };
            };
        };
    };
    FriendshipsController_incoming: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"][];
                };
            };
        };
    };
    FriendshipsController_outgoing: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"][];
                };
            };
        };
    };
    FriendshipsController_accept: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"];
                };
            };
        };
    };
    FriendshipsController_reject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"];
                };
            };
        };
    };
    FriendshipsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    FriendshipsController_block: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FriendshipResponse"];
                };
            };
        };
    };
    PlacesController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceListItemResponse"][];
                };
            };
        };
    };
    PlacesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePlaceDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceResponse"];
                };
            };
        };
    };
    PlacesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceDetailResponse"];
                };
            };
        };
    };
    PlacesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    PlacesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePlaceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceResponse"];
                };
            };
        };
    };
    PlacesController_activity: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
            };
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityLogResponse"][];
                };
            };
        };
    };
    MembersController_acceptInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptInviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceMemberResponse"];
                };
            };
        };
    };
    MembersController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceMemberResponse"][];
                };
            };
        };
    };
    MembersController_add: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceMemberResponse"];
                };
            };
        };
    };
    MembersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    MembersController_updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                memberId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceMemberResponse"];
                };
            };
        };
    };
    MembersController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    MembersController_listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceInviteResponse"][];
                };
            };
        };
    };
    MembersController_createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaceInviteResponse"];
                };
            };
        };
    };
    MembersController_revokeInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                inviteId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    StoragesController_findByLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                labelCode: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageDetailResponse"];
                };
            };
        };
    };
    StoragesController_findAll: {
        parameters: {
            query?: {
                /** @description Only direct children of this storage */
                parentId?: string;
                type?: "ROOM" | "ALMIRAH" | "WARDROBE" | "CABINET" | "SHELF" | "DRAWER" | "BED" | "BOX" | "SUITCASE" | "BAG" | "FRIDGE" | "LOFT" | "RACK" | "DESK" | "SAFE" | "OTHER";
                /** @description Match part of the storage name */
                q?: string;
                /** @description Return only root storages */
                rootOnly?: boolean;
            };
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageListItemResponse"][];
                };
            };
        };
    };
    StoragesController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStorageDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageResponse"];
                };
            };
        };
    };
    StoragesController_tree: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageNodeResponse"][];
                };
            };
        };
    };
    StoragesController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                storageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageDetailResponse"];
                };
            };
        };
    };
    StoragesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                storageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageDeletedResponse"];
                };
            };
        };
    };
    StoragesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                storageId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStorageDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageResponse"];
                };
            };
        };
    };
    ItemsController_attention: {
        parameters: {
            query: {
                withinDays: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttentionResponse"];
                };
            };
        };
    };
    ItemsController_findAll: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                /** @description Free text over name, aliases, tags and description */
                q?: string;
                storageId?: string;
                /** @description Include items in nested storages under storageId */
                includeNested?: boolean;
                status?: "AVAILABLE" | "LENT_OUT" | "CONSUMED" | "LOST" | "DISCARDED";
                visibility?: "SHARED" | "PRIVATE";
                tag?: string;
                category?: string;
                /** @description Only items expiring within this many days */
                expiringInDays?: number;
                /** @description Only items at or below their low-stock threshold */
                lowStock?: boolean;
                sortBy?: "name" | "createdAt" | "updatedAt" | "expiresAt";
                sortOrder?: "asc" | "desc";
            };
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedItemsResponse"];
                };
            };
        };
    };
    ItemsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailResponse"];
                };
            };
        };
    };
    ItemsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailResponse"];
                };
            };
        };
    };
    ItemsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuccessResponse"];
                };
            };
        };
    };
    ItemsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailResponse"];
                };
            };
        };
    };
    ItemsController_history: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemMovementResponse"][];
                };
            };
        };
    };
    ItemsController_move: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemDetailResponse"];
                };
            };
        };
    };
    ItemsController_lend: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LendItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
        };
    };
    ItemsController_returnItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                placeId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemResponse"];
                };
            };
        };
    };
    SearchController_search: {
        parameters: {
            query: {
                page?: number;
                limit?: number;
                /** @description What are you looking for? */
                q: string;
                /** @description Restrict to one place. Omit to search everywhere. */
                placeId?: string;
                /** @description Also return matching storages */
                includeStorages?: boolean;
                /** @description Include deleted/discarded things */
                includeArchived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
        };
    };
}
